### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pierreganty** [pierreganty/mist#29]
on my machine `Darwin Macintosh-2.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64`

`./src/mist --backward ./benchmarks/PN/fms.spec` returns a `Segmentation fault: 11`

the complete output is 
```
Copyright (C) 2002-2015 Pierre Ganty, 2003-2008 Laurent Van Begin, 2014-2015 Pedro Valero.
mist is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
There is absolutely no warranty for mist. See the COPYING for details.


Parsing the problem instance.

./benchmarks/PN/fms.spec
Allocating memory for data structure.. DONE
System has  22 variables,  20 transitions and  2 actual invariants
Can't open file (null) so there won't be data for the graphics
Unsafe region is empty or lies outside the invariants or contains some initial states
The reached symbolic state space is:
Elems:       0 Nodes:     1 Arcs:     0 Layers:  0
Total time of computation (user)   ->  0.000 sec.
                          (system) ->  0.000 sec.
Segmentation fault: 11
```

**Comment by pierreganty** [comment]
@pevalme you posted 60c110b2276d2bc4c0c6579d49d28dfd805be073 to fix the crash.
Can you provide here the stack trace (from gdb) ending with the call `ist_dispose(NULL)` on top which leads to the crash? I am curious since I am almost sure the crash did not happen when we started this project.

**Comment by pevalme** [comment]
```
./benchmarks/PN/fms.spec
Allocating memory for data structure.. DONE
System has  22 variables,  20 transitions and  2 actual invariants
Can't open file (null) so there won't be data for the graphics
Unsafe region is empty or lies outside the invariants or contains some initial states
The reached symbolic state space is:
Elems:       0 Nodes:     1 Arcs:     0 Layers:  0
Total time of computation (user)   ->  0.000 sec.
                          (system) ->  0.000 sec.

Program received signal SIGSEGV, Segmentation fault.
ist_dispose (ST=0x0) at proc.c:418
418		ST->Next = st_Disposed;
(gdb) bt
#0  ist_dispose (ST=0x0) at proc.c:418
#1  0x0805a0dc in backward_basic (system=0x13c689c8, initial_marking=0x13c491a0, frontier=0x13c49158) at mist.c:378
#2  0x08049200 in main (argc=3, argv=0xbffff584) at mist.c:1456
(gdb) 
```

If you look at the function  ```ist_dispose()```:
```
inline void ist_dispose(ST)
	ISTSharingTree *ST;
{

	ST->Next = st_Disposed;
	st_Disposed = ST;
}
```

You can see that if the pointer is NULL, the instruction ```ST->next``` will crash

**Comment by pierreganty** [comment]
I see. Still, I suspect the fix is only patching the leave of the tree, the root cause of the bug being higher up.

**Comment by pierreganty** [comment]
#30 solves this issue.
